// sdks/web/flows/upstream/reference/framework-examples/solid/src/components/tour-banner.tsx
import { TourComponentProps } from "@superboard/flows-js";
import { Component } from "solid-js";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export const TourBanner: Component<Props> = (props) => {
  return (
    <div>
      <h2>{props.title}</h2>
      <p>{props.body}</p>

      {/* In the first step the previous function is undefined */}
      {!!props.previous && <button onClick={props.previous}>Previous</button>}
      <button onClick={props.continue}>Continue</button>
      <button onClick={props.cancel}>Cancel</button>
    </div>
  );
};

// sdks/web/flows/upstream/reference/framework-examples/react/tanstack/src/components/tour-banner.tsx
import type { FC } from "react";
import type { TourComponentProps } from "@superboard/flows-react";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export const TourBanner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        {/* In the first step the previous function is undefined */}
        {props.previous && <button onClick={props.previous}>Previous</button>}
        <button onClick={props.continue}>Continue</button>
        <button onClick={props.cancel}>Cancel</button>
      </div>
    </div>
  );
};
