// sdks/web/flows/upstream/reference/framework-examples/solid/src/flows.tsx
import { onMount } from "solid-js";
import { customElement } from "solid-element";
import { useNavigate } from "@solidjs/router";

import { init } from "@superboard/flows-js";
import { setupJsComponents } from "@superboard/flows-js-components";

import * as components from "@superboard/flows-js-components/components";
import * as tourComponents from "@superboard/flows-js-components/tour-components";
import * as surveyComponents from "@superboard/flows-js-components/survey-components";

// Don't forget to import the CSS styles for Flows components
import "@superboard/flows-js-components/index.css";

import { Banner as SolidBanner } from "~/components/banner";
import { TourBanner as SolidTourBanner } from "~/components/tour-banner";

export const Flows = () => {
  const navigate = useNavigate();

  onMount(() => {
    init({
      projectId: "YOUR_PROJECT_ID",
      userId: "YOUR_USER_ID",
      environment: "production",
      onNavigate: (href, event) => {
        event.preventDefault();

        navigate(href);
      },
    });

    const Banner = customElement(
      "flows-banner",
      {
        // Define prop keys with default values
        title: "",
        body: "",
        close: () => {},
        __flows: { id: "", workflowId: "" },
      },
      SolidBanner,
    );
    const TourBanner = customElement(
      "flows-tour-banner",
      {
        // Define prop keys with default values
        title: "",
        body: "",
        previous: () => {},
        continue: () => {},
        cancel: () => {},
        __flows: { id: "", workflowId: "" },
      },
      SolidTourBanner,
    );

    setupJsComponents({
      components: {
        ...components,
        // Example of custom "Banner" component
        Banner,
      },
      tourComponents: {
        ...tourComponents,
        // Example of custom "Banner" component for tours
        Banner: TourBanner,
      },
      surveyComponents: {
        ...surveyComponents,
      },
    });
  });

  return <flows-floating-blocks />;
};

// sdks/flows/upstream/reference/framework-examples/react/next/app/flows.tsx
"use client";

import { FC, ReactNode } from "react";
import Link from "next/link";
import { FlowsProvider } from "@superboard/flows-react";
import * as components from "@superboard/flows-react-components";
import * as tourComponents from "@superboard/flows-react-components/tour";
import * as surveyComponents from "@superboard/flows-react-components/survey";
import "@superboard/flows-react-components/index.css";

import { Banner } from "@/components/banner";
import { TourBanner } from "@/components/tour-banner";

type Props = {
  children?: ReactNode;
};

export const Flows: FC<Props> = ({ children }) => {
  return (
    <FlowsProvider
      projectId="YOUR_PROJECT_ID"
      userId="YOUR_USER_ID"
      environment="production"
      components={{
        ...components,
        Banner: Banner,
      }}
      tourComponents={{
        ...tourComponents,
        Banner: TourBanner,
      }}
      surveyComponents={{ ...surveyComponents }}
      LinkComponent={Link}
    >
      {children}
    </FlowsProvider>
  );
};
