// sdks/web/flows/upstream/reference/framework-examples/lit/src/banner.ts
import { html, LitElement } from "lit";
import { property } from "lit/decorators.js";

type Props = {
  title: string;
  body: string;

  close: () => void;
};

export class Banner extends LitElement implements Props {
  @property()
  title = "";

  @property()
  body = "";

  @property()
  close = () => {};

  render() {
    return html`
      <div>
        <p>${this.title}</p>
        <p>${this.body}</p>
        <div>
          <button @click=${this.close}>Close</button>
        </div>
      </div>
    `;
  }
}

// sdks/web/flows/upstream/reference/framework-examples/react/vite/app/components/banner.tsx
import type { FC } from "react";

type Props = {
  title: string;
  body: string;

  close: () => void;
};

export const Banner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        <button onClick={props.close}>Close</button>
      </div>
    </div>
  );
};
