// sdks/web/flows/upstream/reference/framework-examples/react/tanstack/src/components/banner.tsx
import type { FC } from "react";
import { ComponentProps } from "@superboard/flows-react";

type Props = ComponentProps<{
  title: string;
  body: string;

  close: () => void;
}>;

export const Banner: FC<Props> = (props) => {
  return (
    <div>
      <p>{props.title}</p>
      <p>{props.body}</p>
      <div>
        <button onClick={props.close}>Close</button>
      </div>
    </div>
  );
};

// sdks/flows/upstream/reference/framework-examples/angular/src/app/banner/banner.ts
import { Component, Input } from '@angular/core';
import { ComponentProps, FlowsProperties } from '@superboard/flows-js';

type Props = ComponentProps<{
  title: string;
  body: string;

  close: () => void;
}>;

@Component({
  selector: 'app-banner',
  imports: [],
  templateUrl: './banner.html',
  styleUrl: './banner.css',
})
export class Banner implements Props {
  @Input() title = '';
  @Input() body = '';

  @Input({ required: true }) close!: () => void;
  @Input() __flows!: FlowsProperties;
}
