// sdks/flows/upstream/reference/framework-examples/react/next/components/tour-banner.tsx
"use client";

import { FC } from "react";
import { TourComponentProps } from "@superboard/flows-react";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export const TourBanner: FC<Props> = (props) => {
  return (
    <div className="rounded border border-gray-400 p-4 w-full">
      <p className="mb-3 text-base font-bold">{props.title}</p>
      <p className="text-sm mb-4">{props.body}</p>
      <div className="flex justify-end gap-1">
        {/* In the first step the previous function is undefined */}
        {props.previous && <button onClick={props.previous}>Previous</button>}
        <button onClick={props.continue}>Continue</button>
        <button onClick={props.cancel}>Cancel</button>
      </div>
    </div>
  );
};

// sdks/web/flows/upstream/reference/framework-examples/solid/src/components/tour-banner.tsx
import { TourComponentProps } from "@superboard/flows-js";
import { Component } from "solid-js";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export const TourBanner: Component<Props> = (props) => {
  return (
    <div>
      <h2>{props.title}</h2>
      <p>{props.body}</p>

      {/* In the first step the previous function is undefined */}
      {!!props.previous && <button onClick={props.previous}>Previous</button>}
      <button onClick={props.continue}>Continue</button>
      <button onClick={props.cancel}>Cancel</button>
    </div>
  );
};
