// sdks/flows/upstream/reference/framework-examples/lit/src/tour-banner.ts
import type { FlowsProperties, TourComponentProps } from "@superboard/flows-js";
import { html, LitElement } from "lit";

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

export class TourBanner extends LitElement implements Props {
  title = "";

  body = "";

  previous?: () => void;
  continue: () => void;
  cancel: () => void;

  __flows: FlowsProperties;

  render() {
    return html`
      <div>
        <p>${this.title}</p>
        <p>${this.body}</p>
        <div>
          <!-- In the first step the previous function is undefined -->
          ${this.previous && html`<button @click=${this.previous}>Previous</button>`}
          <button @click=${this.continue}>Continue</button>
          <button @click=${this.cancel}>Cancel</button>
        </div>
      </div>
    `;
  }
}

// sdks/flows/upstream/reference/framework-examples/angular/src/app/tour-banner/tour-banner.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { FlowsProperties, TourComponentProps } from '@superboard/flows-js';

type Props = TourComponentProps<{
  title: string;
  body: string;
}>;

@Component({
  selector: 'app-tour-banner',
  imports: [CommonModule],
  templateUrl: './tour-banner.html',
  styleUrl: './tour-banner.css',
})
export class TourBanner implements Props {
  @Input() title = '';
  @Input() body = '';

  @Input() continue!: () => void;
  @Input() previous!: () => void;
  @Input() cancel!: () => void;

  @Input() __flows!: FlowsProperties;
}
